import pytest
from sqlalchemy import inspect

from trueup.store.models import Base

EXPECTED_COLUMNS = {
    "company_vendors": [
        "vendor_id",
        "vendor_name",
        "vendor_category",
        "billing_cadence",
        "default_currency",
        "billing_contact_email",
        "is_active",
    ],
    "company_contracts": [
        "contract_row_id",
        "contract_id",
        "contract_version",
        "vendor_id",
        "contract_name",
        "status",
        "effective_start_date",
        "effective_end_date",
        "billing_model",
        "base_rate",
        "rate_unit",
        "billing_frequency",
        "escalator_percent",
        "escalator_effective_date",
        "service_owner_id",
        "procurement_owner_id",
        "contract_text",
    ],
    "company_purchase_orders": [
        "po_id",
        "po_number",
        "vendor_id",
        "contract_id",
        "status",
        "order_type",
        "entity_id",
        "cost_center",
        "po_owner_id",
        "approved_total",
        "currency",
        "service_start_date",
        "service_end_date",
        "gl_account",
        "description",
        "line_items_json",
    ],
    "company_service_evidence": [
        "service_evidence_id",
        "vendor_id",
        "contract_id",
        "po_id",
        "service_start_date",
        "service_end_date",
        "evidence_type",
        "quantity",
        "unit",
        "accepted_amount",
        "source_system",
        "confirmed_by_person_id",
        "confirmation_status",
        "created_at",
    ],
    "company_non_po_spend": [
        "non_po_spend_id",
        "transaction_date",
        "month",
        "vendor_id",
        "merchant_name",
        "spend_source",
        "cardholder_id",
        "cost_center",
        "gl_account",
        "amount",
        "currency",
        "transaction_status",
        "ap_invoice_id",
        "description",
        "is_accrued",
        "gl_entry_id",
        "created_at",
        "updated_at",
    ],
    "company_ap_invoices": [
        "invoice_id",
        "vendor_id",
        "invoice_number",
        "invoice_date",
        "received_at",
        "service_start_date",
        "service_end_date",
        "amount",
        "currency",
        "po_id",
        "contract_id",
        "status",
        "duplicate_flag",
        "credit_flag",
        "description",
        "line_items_json",
        "created_at",
        "updated_at",
    ],
    "company_gl_entries": [
        "gl_entry_id",
        "period",
        "posting_date",
        "vendor_id",
        "obligation_id",
        "entry_type",
        "status",
        "description",
        "lines_json",
        "source_workpaper_id",
        "reversal_of_gl_entry_id",
        "created_at",
    ],
    "company_config": ["config_key", "config_value_json", "updated_at"],
    "trueup_obligations": [
        "obligation_id",
        "vendor_id",
        "period",
        "contract_id",
        "po_id",
        "non_po_group_key",
        "service_start_date",
        "service_end_date",
        "purchase_type",
        "invoice_status",
        "evidence_status",
        "workflow_stage",
        "next_action",
        "assigned_agent",
        "accrual_status",
        "risk_level",
        "current_workpaper_id",
        "matched_invoice_id",
        "opened_at",
        "updated_at",
        "resolved_at",
    ],
    "trueup_evidence": [
        "evidence_id",
        "obligation_id",
        "evidence_type",
        "source_table",
        "source_id",
        "fact",
        "value_json",
        "source_excerpt",
        "confidence",
        "status",
        "created_by_agent",
        "created_at",
    ],
    "trueup_workpapers": [
        "workpaper_id",
        "obligation_id",
        "period",
        "estimation_method",
        "proposed_amount",
        "currency",
        "calculation_expression",
        "calculation_inputs_json",
        "expense_account",
        "accrual_liability_account",
        "cost_center",
        "status",
        "policy_decision",
        "policy_summary",
        "controller_decision",
        "controller_notes",
        "journal_entry_json",
        "created_by_agent",
        "created_at",
        "updated_at",
    ],
    "trueup_agent_runs": [
        "run_id",
        "obligation_id",
        "workpaper_id",
        "agent_name",
        "action",
        "status",
        "facts_used_json",
        "decision_summary",
        "uncertainties_json",
        "output_summary",
        "input_record_ids_json",
        "output_record_ids_json",
        "created_at",
    ],
    "trueup_learning_rules": [
        "learning_id",
        "obligation_id",
        "workpaper_id",
        "invoice_id",
        "actual_amount",
        "accrual_amount",
        "variance_amount",
        "variance_percent",
        "root_cause",
        "root_cause_summary",
        "candidate_rule_json",
        "replay_result_json",
        "status",
        "approved_by",
        "created_at",
        "updated_at",
    ],
}

NULLABLE = {
    "company_vendors": {"billing_contact_email"},
    "company_contracts": {
        "effective_end_date",
        "base_rate",
        "rate_unit",
        "escalator_percent",
        "escalator_effective_date",
        "service_owner_id",
        "procurement_owner_id",
    },
    "company_purchase_orders": {"contract_id", "service_start_date", "service_end_date"},
    "company_service_evidence": {
        "contract_id",
        "po_id",
        "quantity",
        "unit",
        "accepted_amount",
        "confirmed_by_person_id",
    },
    "company_non_po_spend": {"vendor_id", "cardholder_id", "ap_invoice_id", "gl_entry_id"},
    "company_ap_invoices": {
        "service_start_date",
        "service_end_date",
        "po_id",
        "contract_id",
        "line_items_json",
    },
    "company_gl_entries": {
        "vendor_id",
        "obligation_id",
        "source_workpaper_id",
        "reversal_of_gl_entry_id",
    },
    "company_config": set(),
    "trueup_obligations": {
        "contract_id",
        "po_id",
        "non_po_group_key",
        "assigned_agent",
        "current_workpaper_id",
        "matched_invoice_id",
        "resolved_at",
    },
    "trueup_evidence": {"source_excerpt"},
    "trueup_workpapers": {"controller_decision", "controller_notes"},
    "trueup_agent_runs": {"obligation_id", "workpaper_id", "uncertainties_json"},
    "trueup_learning_rules": {
        "invoice_id",
        "variance_percent",
        "candidate_rule_json",
        "replay_result_json",
        "approved_by",
    },
}


def test_there_are_exactly_thirteen_tables():
    assert set(Base.metadata.tables) == set(EXPECTED_COLUMNS)
    assert len(EXPECTED_COLUMNS) == 13


@pytest.mark.parametrize("table", sorted(EXPECTED_COLUMNS))
def test_table_columns_match_the_spec_exactly(store_engine, table):
    columns = [column["name"] for column in inspect(store_engine).get_columns(table)]
    assert columns == EXPECTED_COLUMNS[table]


@pytest.mark.parametrize("table", sorted(EXPECTED_COLUMNS))
def test_table_nullability_matches_the_spec(store_engine, table):
    columns = inspect(store_engine).get_columns(table)
    nullable = {column["name"] for column in columns if column["nullable"]}
    assert nullable == NULLABLE[table]
