"""Allowed values for every enumerated column in the 13-table schema.

Members are strings, so columns stay plain TEXT and members compare equal to their values.
"""

from enum import StrEnum


class VendorCategory(StrEnum):
    SAAS = "SAAS"
    CLOUD = "CLOUD"
    AI_CREDITS = "AI_CREDITS"
    DATA = "DATA"
    CONSULTING = "CONSULTING"
    MARKETING = "MARKETING"
    HARDWARE = "HARDWARE"
    OFFICE = "OFFICE"
    TRAVEL = "TRAVEL"
    OTHER = "OTHER"


class BillingCadence(StrEnum):
    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    ANNUAL = "ANNUAL"
    USAGE_BASED = "USAGE_BASED"
    AD_HOC = "AD_HOC"


class ContractStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    EXPIRED = "EXPIRED"
    TERMINATED = "TERMINATED"


class BillingModel(StrEnum):
    FIXED_FEE = "FIXED_FEE"
    USAGE_BASED = "USAGE_BASED"
    SEAT_BASED = "SEAT_BASED"
    MILESTONE_BASED = "MILESTONE_BASED"
    TIME_AND_MATERIALS = "TIME_AND_MATERIALS"
    HYBRID = "HYBRID"


class RateUnit(StrEnum):
    MONTH = "MONTH"
    API_CALL = "API_CALL"
    COMPUTE_HOUR = "COMPUTE_HOUR"
    SEAT = "SEAT"
    CONSULTING_HOUR = "CONSULTING_HOUR"
    PROJECT = "PROJECT"


class BillingFrequency(StrEnum):
    MONTHLY_IN_ARREARS = "MONTHLY_IN_ARREARS"
    MONTHLY_IN_ADVANCE = "MONTHLY_IN_ADVANCE"
    QUARTERLY = "QUARTERLY"
    ANNUAL = "ANNUAL"
    VARIABLE = "VARIABLE"


class POStatus(StrEnum):
    APPROVED = "APPROVED"
    OPEN = "OPEN"
    FULLY_BILLED = "FULLY_BILLED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    AMENDED = "AMENDED"


class OrderType(StrEnum):
    STANDARD = "STANDARD"
    FRAMEWORK = "FRAMEWORK"
    BLANKET = "BLANKET"
    PROJECT = "PROJECT"


class ItemCategory(StrEnum):
    SERVICE = "SERVICE"
    MATERIAL = "MATERIAL"
    BLANKET_LIMIT = "BLANKET_LIMIT"
    ENHANCED_LIMIT = "ENHANCED_LIMIT"


class ServiceEvidenceType(StrEnum):
    SYSTEM_USAGE = "SYSTEM_USAGE"
    GOODS_RECEIPT = "GOODS_RECEIPT"
    TIMESHEET = "TIMESHEET"
    SEAT_COUNT = "SEAT_COUNT"
    MILESTONE_ACCEPTANCE = "MILESTONE_ACCEPTANCE"
    MANUAL_CONFIRMATION = "MANUAL_CONFIRMATION"


class SourceSystem(StrEnum):
    ENGINEERING_PLATFORM = "ENGINEERING_PLATFORM"
    PROJECT_MANAGEMENT = "PROJECT_MANAGEMENT"
    PROCUREMENT = "PROCUREMENT"
    WAREHOUSE = "WAREHOUSE"
    MANUAL = "MANUAL"


class ConfirmationStatus(StrEnum):
    SYSTEM_VERIFIED = "SYSTEM_VERIFIED"
    OWNER_CONFIRMED = "OWNER_CONFIRMED"
    PENDING = "PENDING"
    DISPUTED = "DISPUTED"
    REJECTED = "REJECTED"


class SpendSource(StrEnum):
    PROCUREMENT_CARD = "PROCUREMENT_CARD"
    CORPORATE_CARD = "CORPORATE_CARD"
    DIRECT_NON_PO_INVOICE = "DIRECT_NON_PO_INVOICE"
    EXPENSE_REIMBURSEMENT = "EXPENSE_REIMBURSEMENT"


class TransactionStatus(StrEnum):
    PENDING = "PENDING"
    SETTLED = "SETTLED"
    POSTED_TO_AP = "POSTED_TO_AP"
    VOIDED = "VOIDED"
    REFUNDED = "REFUNDED"
    DISPUTED = "DISPUTED"


class APInvoiceStatus(StrEnum):
    IN_QUEUE = "IN_QUEUE"
    PENDING_REVIEW = "PENDING_REVIEW"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    POSTED = "POSTED"
    PAID = "PAID"
    ON_HOLD = "ON_HOLD"
    REJECTED = "REJECTED"
    VOIDED = "VOIDED"


class GLEntryType(StrEnum):
    AP_INVOICE = "AP_INVOICE"
    ACCRUAL = "ACCRUAL"
    ACCRUAL_REVERSAL = "ACCRUAL_REVERSAL"
    TRUE_UP = "TRUE_UP"
    MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT"


class GLEntryStatus(StrEnum):
    DRAFT = "DRAFT"
    POSTED = "POSTED"
    REVERSED = "REVERSED"
    VOIDED = "VOIDED"


class PurchaseType(StrEnum):
    FIXED_RECURRING = "FIXED_RECURRING"
    USAGE_BASED = "USAGE_BASED"
    RECEIPT_BASED = "RECEIPT_BASED"
    MILESTONE_BASED = "MILESTONE_BASED"
    NON_PO_CARD_SPEND = "NON_PO_CARD_SPEND"
    NON_PO_DIRECT_SPEND = "NON_PO_DIRECT_SPEND"
    PREPAID = "PREPAID"
    UNKNOWN = "UNKNOWN"


class InvoiceStatus(StrEnum):
    NOT_SEARCHED = "NOT_SEARCHED"
    INVOICE_FOUND = "INVOICE_FOUND"
    MISSING = "MISSING"
    AMBIGUOUS = "AMBIGUOUS"
    MATCHED_AFTER_CLOSE = "MATCHED_AFTER_CLOSE"


class EvidenceStatus(StrEnum):
    NOT_COLLECTED = "NOT_COLLECTED"
    SUFFICIENT = "SUFFICIENT"
    MISSING_USAGE = "MISSING_USAGE"
    MISSING_RATE = "MISSING_RATE"
    MISSING_SERVICE_CONFIRMATION = "MISSING_SERVICE_CONFIRMATION"
    CONFLICTING = "CONFLICTING"


class WorkflowStage(StrEnum):
    DETECTED = "DETECTED"
    SEARCHING_AP = "SEARCHING_AP"
    GATHERING_EVIDENCE = "GATHERING_EVIDENCE"
    CLASSIFYING = "CLASSIFYING"
    ESTIMATING = "ESTIMATING"
    AWAITING_OUTREACH = "AWAITING_OUTREACH"
    AWAITING_CONTROLLER = "AWAITING_CONTROLLER"
    READY_TO_DRAFT = "READY_TO_DRAFT"
    AWAITING_ACTUAL_INVOICE = "AWAITING_ACTUAL_INVOICE"
    RECONCILING = "RECONCILING"
    CLOSED_NO_ACCRUAL = "CLOSED_NO_ACCRUAL"
    CLOSED = "CLOSED"
    BLOCKED = "BLOCKED"


class NextAction(StrEnum):
    SEARCH_AP = "SEARCH_AP"
    GATHER_EVIDENCE = "GATHER_EVIDENCE"
    CLASSIFY = "CLASSIFY"
    ESTIMATE = "ESTIMATE"
    VERIFY_POLICY = "VERIFY_POLICY"
    SEND_OUTREACH = "SEND_OUTREACH"
    CONTROLLER_REVIEW = "CONTROLLER_REVIEW"
    DRAFT_ENTRY = "DRAFT_ENTRY"
    WAIT_FOR_INVOICE = "WAIT_FOR_INVOICE"
    MATCH_AND_TRUE_UP = "MATCH_AND_TRUE_UP"
    EVALUATE_LEARNING = "EVALUATE_LEARNING"
    NONE = "NONE"


class AccrualStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    NOT_NEEDED = "NOT_NEEDED"
    DRAFTED = "DRAFTED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    POSTED_SIMULATED = "POSTED_SIMULATED"
    TRUE_UP_COMPLETE = "TRUE_UP_COMPLETE"


class EvidenceCardType(StrEnum):
    CONTRACT_TERM = "CONTRACT_TERM"
    PO_DETAIL = "PO_DETAIL"
    SERVICE_USAGE = "SERVICE_USAGE"
    SERVICE_RECEIPT = "SERVICE_RECEIPT"
    NON_PO_TRANSACTION = "NON_PO_TRANSACTION"
    AP_SEARCH = "AP_SEARCH"
    GL_HISTORY = "GL_HISTORY"
    INVOICE = "INVOICE"
    OUTREACH_RESPONSE = "OUTREACH_RESPONSE"
    CONTROLLER_DECISION = "CONTROLLER_DECISION"


class EvidenceCardStatus(StrEnum):
    VERIFIED = "VERIFIED"
    PENDING = "PENDING"
    CONFLICTING = "CONFLICTING"
    SUPERSEDED = "SUPERSEDED"


class EstimationMethod(StrEnum):
    FIXED_CONTRACT_RATE = "FIXED_CONTRACT_RATE"
    USAGE_TIMES_RATE = "USAGE_TIMES_RATE"
    RECEIVED_QUANTITY_TIMES_PRICE = "RECEIVED_QUANTITY_TIMES_PRICE"
    MILESTONE_ACCEPTED_AMOUNT = "MILESTONE_ACCEPTED_AMOUNT"
    HISTORICAL_RUN_RATE = "HISTORICAL_RUN_RATE"
    NON_PO_BALANCE_SUM = "NON_PO_BALANCE_SUM"
    PREPAID_AMORTIZATION = "PREPAID_AMORTIZATION"


class WorkpaperStatus(StrEnum):
    DRAFT = "DRAFT"
    AWAITING_POLICY = "AWAITING_POLICY"
    AWAITING_OUTREACH = "AWAITING_OUTREACH"
    AWAITING_CONTROLLER = "AWAITING_CONTROLLER"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    POSTED_SIMULATED = "POSTED_SIMULATED"
    TRUE_UP_COMPLETE = "TRUE_UP_COMPLETE"


class PolicyDecision(StrEnum):
    NOT_RUN = "NOT_RUN"
    PERMIT = "PERMIT"
    REQUIRE_OUTREACH = "REQUIRE_OUTREACH"
    REQUIRE_CONTROLLER = "REQUIRE_CONTROLLER"
    BLOCK = "BLOCK"


class ControllerDecision(StrEnum):
    APPROVE = "APPROVE"
    APPROVE_WITH_ADJUSTMENT = "APPROVE_WITH_ADJUSTMENT"
    REJECT = "REJECT"
    REQUEST_MORE_EVIDENCE = "REQUEST_MORE_EVIDENCE"


class AgentRunStatus(StrEnum):
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    ESCALATED = "ESCALATED"
    FAILED = "FAILED"


class RootCause(StrEnum):
    MISSED_ESCALATOR = "MISSED_ESCALATOR"
    USAGE_VARIANCE = "USAGE_VARIANCE"
    SCOPE_CHANGE = "SCOPE_CHANGE"
    TIMING_DIFFERENCE = "TIMING_DIFFERENCE"
    MULTI_PERIOD_INVOICE = "MULTI_PERIOD_INVOICE"
    DUPLICATE_NON_PO_ACCRUAL = "DUPLICATE_NON_PO_ACCRUAL"
    SOURCE_DATA_ERROR = "SOURCE_DATA_ERROR"
    UNKNOWN = "UNKNOWN"


class LearningStatus(StrEnum):
    TRUE_UP_RECORDED = "TRUE_UP_RECORDED"
    DIAGNOSED = "DIAGNOSED"
    RULE_CANDIDATE = "RULE_CANDIDATE"
    REPLAY_PASSED = "REPLAY_PASSED"
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    REVOKED = "REVOKED"
